### ISSUE TITLE
Support for pipe operator (%>%) and dplyr indentation

### ISSUE THREAD

**Issue by enrico16** [jcfaria/Vim-R-plugin#160] opened 2015-02-19 12:15 UTC
Would it be possible to make vim indent correctly code written with the pipe (aka chain) operator %>%?
This is extensively used in dplyr-like workflows, e.g.:

```r
flights %>%
    group_by(year, month, day) %>%
    select(arr_delay, dep_delay) %>%
    summarise(
        arr = mean(arr_delay, na.rm = TRUE),
        dep = mean(dep_delay, na.rm = TRUE)
    ) %>%
    filter(arr > 30 | dep > 30)
```

Thanks!

**Comment by klmr** [comment] 2015-02-19 12:17
There’s really no need to support `%>%` specifically (nor would this be a good idea, I think). Instead, a line ended by *any* binary operator should probably result in the next line being indented accordingly.

**Comment by jalvesaq** [comment] 2015-02-19 13:08
@enrico16 I did not understand your example. You have indented after the first `%>%`, but not after the others. When should the indentation be increased one level and when should it be decreased one level?

Note that the indent/r.vim needs to be completely rewritten because the current one is too complicated and slow, but I am no longer willing to spend time improving the indentation. I can implement what you are requesting only if it is easy to do in the current script without breaking the indentation in https://github.com/jcfaria/Vim-R-plugin/blob/master/r-plugin/indent_test_noalign.R

**Comment by enrico16** [comment] 2015-02-19 15:11
@jalvesaq: That's how it should look, have a look at this article, section "Chaining": 
http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html

Or this:
 http://blog.revolutionanalytics.com/2014/07/magrittr-simplifying-r-code-with-pipes.html

I think @klmr suggestion is a good one but indentation should occur only after the first binary operator.

Is this feasible?
Thanks!

**Comment by jalvesaq** [comment] 2015-02-19 15:29
Something must indicate the end of the indentation. Is it an empty line? Is the algorithm below correct?

   1. If the previous line has the pattern `%.%$` and it is the first line in the paragraph to have this pattern, then increase indentation.
   2. If this is the first line after an empty line and the indentation of the previous line was increased by the occurrence of the pattern `%.%$` one or more lines above, then decrease the indentation.

**Comment by klmr** [comment] 2015-02-19 15:44
The end of the indentation is indicated by a lack of a trailing binary operator. It’s *not* necessarily an empty line:

```r
x = letters %>%
    sapply(strupper)
message(x)
```

The pattern is off as well. **Any** binary operator should trigger this. For instance, ggplot2 uses the common pattern

```r
ggplot(data, aes(…)) +
    geom_points() +
    theme_bw() +
    scale_fill_discrete()
```

… and this is generalisable to non-ggplot2, non-dplyr code.

**Comment by enrico16** [comment] 2015-02-19 16:39
@jalvesaq, @klmr hit the nail on the head: 
1. The end of the indentation is indicated by a lack of a trailing binary operator;
2. Any binary operator should trigger this indentation.

**Comment by jalvesaq** [comment] 2015-02-19 16:52
So, it seems that it is better to create an option, like `r_indent_op_pattern` and let the user define its value. Being optional, it is not critically important that the new indentation rule does not break any old rule. I will try to implement something later today, and I hope that it does not take too much time.

**Comment by jalvesaq** [comment] 2015-02-20 01:11
I partially implemented the feature: https://github.com/jcfaria/Vim-R-plugin/commit/47e1037013fe347b738f69a465a308b97123aa0d. To test it, I have put the following in my `vimrc`:

```vim
let r_indent_op_pattern = '%[^%]*%$'
```

and got the following indentation:

```s
x = letters %>%
    sapply(strupper)
message(x)

flights %>%
    group <- by(year, month, day) %>%
    select(arr <- delay, dep <- delay) %>%
    endop <- "END"
x <- 0
```

However, the complete sample code in the first message of the feature request is not correctly indented:

```s
flights %>%
    group <- by(year, month, day) %>%
    select(arr <- delay, dep <- delay) %>%
    summarise(
              arr = mean(arr <- delay, na.rm = TRUE),
              dep = mean(dep <- delay, na.rm = TRUE)
             ) %>%
    filter(arr > 30 | dep > 30)
x <- 0
```

Notes:
   - I had to copy indent/r.vim to /usr/local/share/vim/vim74/indent/r.vim because Vim was not reading the script from the Vim-R-plugin.
   -  The first 545 lines of `r-plugin/indent_test.R` are still correctly indented.

**Comment by jalvesaq** [comment] 2015-02-20 04:52
New change: https://github.com/jcfaria/Vim-R-plugin/commit/eff056d0210726a3ff1e1a0aa0ec5c3857fceac2. The value of `r_indent_op_pattern` now is defined in the `indent/r.vim` script. I added math operators which fixed one of the bugs described in `r-plugin/indent_test.R` (which I also updated: https://github.com/jcfaria/Vim-R-plugin/commit/1c3ea48db2c12ffb3b7ca22cef819d21a5ecab38). I could not add `&` and `|` because it would break the correct indentation in part of the code of `r-plugin/indent_test.R`.

@enrico16 and @klmr please tell me if you find a better value for `r_indent_op_pattern` or if you can improve the code of `indent/r.vim`. If you find values that are better for some people but not for all, we can document the option `r_indent_op_pattern`.

**Comment by enrico16** [comment] 2015-02-20 12:41
@jalvesaq: Thanks for taking the time to look into this.

I think there is something wrong with the default `r_indent_op_pattern` value `\(+\|-\|\*\|/\|=\|\~\|%[^%]*%\)$`.

Code with `%>%` and `+` operators is still not indented correctly.

Adding let `r_indent_op_pattern = '%[^%]*%$'` in my `~/.vimrc` makes the indentation right for `%>%` but (obviously) not for `+`.

**Comment by jalvesaq** [comment] 2015-02-20 16:12
Here, I get this indentation: https://github.com/jcfaria/Vim-R-plugin/blob/master/r-plugin/indent_test.R#L545-574

I think we can simplify the pattern to:

```vim
let r_indent_op_pattern = '\(+\|-\|\*\|/\|=\|\~\|%\)$'
```

Note: Vim's documentation says that the 'magic' option interferes in how patterns are interpreted.

**Comment by enrico16** [comment] 2015-02-20 16:36
Yes, sorry, it works. For some reason it doesn't work if you use a binary operator on the first line of your file, which is why my tests were failing.

The simplified version looks fine to me.

Thanks!

**Comment by jalvesaq** [comment] 2015-02-20 16:53
It is because I need to check the two previous lines to decide to keep, decrease or increase the indentation. I could complicate the test to catch the case of your test, but I think it is better to let this minor bug in the script than to make it more complicated and slow than it already is.

**Comment by enrico16** [comment] 2015-02-20 16:55
Sure - not a problem at all.

**Comment by jalvesaq** [comment] 2015-02-20 17:20
Thanks for requesting the feature and for the feedback. Although the changes did not fix all reported problems, I am closing the issue because I do not have time to do improvements in the indentation algorithm.

**Closed by jalvesaq** 2015-02-20 17:20 UTC

**Comment by jpmorris** [comment] 2015-12-02 18:29
I've tried the above r_indent_op_pattern lines and I can't get the OP example to work. Any long mutate(..) with line breaks seems to break indentation.  I have the newest plugin that vundle will update to and the newest runtime files.  (Worse yet, the sample indentation indent_test.R code breaks well before expected.)  I understand the indentation code is a nightmare and not many bugs will be able to be fixed, but I'd at least like to get this dplyr stuff working as others here have done here.  I've tried a basically blank vimrc file but still couldnt get it to work.  Was there a regression?  Or maybe I need something in my vimrc file that others in this thread have?  Is it still working for everyone? Thanks.

**Comment by jalvesaq** [comment] 2015-12-02 19:08
Code with commands spanning multiple lines are not correctly indented. The code below looks like correctly indented to me:

```r
x = letters %>%
    sapply(strupper)
message(x)

flights %>%
    group <- by(year, month, day) %>%
    select(arr <- delay, dep <- delay) %>%
    endop <- "END"
x <- 0
```

**Comment by jpmorris** [comment] 2015-12-02 21:30
Ok I think I misunderstood when @enricoferrero said 'it works'.  So you're saying the pipe works, but not for multi-line commands.  My workaround is to manually format the last line of broken blocks so that '=' formatting (that is pressing the '=' key) doesn't break in subsequent blocks.  This seems to work.  I am getting strange behavior such as improperly formatted blocks not formatting correctly for example the line:

```
df <- df %>% group_by(test) %>% arrange(test2)
```

When I insert line breaks after the pipes I get an '=' formatting that is either improper or breaks subsequent blocks.  I know it sounds very strange, but when I manually type out the line (and allow autoindent to place my cursor), I don't have this problem.  

Maybe I'm just very confused.  But this is just an aside.  I will use the workaround of 
 manually formatting the improper indents and use '=' indenting where it works. Thanks.

**Comment by pnep** [comment] 2015-12-23 23:46
Would there be a quick fix to support shorthand function, i.e. function defined by {...} in the pipe chain. In the following, the last line should be unindented:

    err <- (a - A.real) %>%
      abs %>%
      sum %>%
      { ./2 }
      errors <- c(errors, err)

**Comment by jalvesaq** [comment] 2015-12-24 10:20
@pnep See: https://github.com/jalvesaq/R-Vim-runtime/commit/604aa58558ace943fb09b7b7f1835e35b4de92f0

**Comment by pnep** [comment] 2015-12-28 23:16
It works! Thanks a lot for your quick reply. I forgot to mention the multiple line case. Is it still easy to fix:

    err <- (a - A.real) %>%
    {
      ./2 
    }
      errors <- c(errors, err)

Happy holiday!

**Comment by jalvesaq** [comment] 2015-12-29 08:44
Sorry, but I couldn't fix this last one. What you can do is:
```
err <- (a - A.real) %>% {
    ./2
}
errors <- c(errors, err)
```

**Comment by pnep** [comment] 2015-12-31 05:21
This workaround works fine. Thank you

**Comment by pnep** [comment] 2016-01-04 03:27
Hi again, I found that if there is spaces at the end of the first line, the formatting is not correct:

  err <- theta$A - theta2$A %>% [space]
    { . * . } %>%
      sum

Could the algorithm automatically remove trailing spaces since they are hardly recognized. I think this would be very useful.

**Comment by jalvesaq** [comment] 2016-01-05 01:00
Thanks for reporting the trailing spaces bug! It is fixed now: https://github.com/jalvesaq/R-Vim-runtime/commit/af44f50da8a6e573cba02867088372c7d0839b53

**Comment by pnth** [comment] 2016-01-20 01:40
Could you also add support for right assignment operator:

```R
	((a - a.real) %>%
	 abs %>%
	 graph.adjacency(mode='undirected') ->
 g.diff)
```
Many thanks

**Comment by jalvesaq** [comment] 2016-01-20 08:29
What is your suggestion of key to be mapped to right assignment operator?

**Comment by pnth** [comment] 2016-01-29 05:42
I think the line could be transformed with ```->``` replaced by some key like ```%-%```. When formatted, reverting it back. Is this possible? I am new to vimscript.

**Comment by klmr** [comment] 2016-01-29 14:29
I have to say, I find @pnth’s use and indentation of the `->` operator very idiosyncratic: this isn’t the way I would indent it, and I don’t think it is/should be the way it’s usually indented. As such, it would make for an awkward default. If at all, it should be activated via an option.

**Comment by jalvesaq** [comment] 2016-01-29 14:46
It could be implemented as an option, but, in any case, it does not seem to be easy to implement. If someone does a pull request, I may apply it, but I'm not going to write the code for this.

**Comment by pnth** [comment] 2016-02-18 02:13
I saw the following indentation of `<-` correct. Could `->` be indented similarly using the similar code?
```R
  ds <-
    ReadJson("db-motion-cache.json") %>%
    arrange(time) %>%
    subset(from <= time & time <= to)
```

**Comment by jalvesaq** [comment] 2016-02-18 09:42
@pnth It also seems better to me to indent the code as you suggested, and was easy to make the change in indent/r.vim. See: https://github.com/jalvesaq/R-Vim-runtime/commit/ff9b08c4682eab4d2ff71338366254e5ff512209
