### ISSUE TITLE
gvim windows stuck on top on Win 7 and 8.1

### ISSUE THREAD

**Issue by azvoleff** [jcfaria/Vim-R-plugin#164] opened 2015-03-23 21:54 UTC
When running Windows (tested on Win 7 and Win 8.1), a change in 3c2be99ef57ffc14acca34ce4e3453eab01873b9 leads to gvim windows with R scripts in them remaining "on top" (in front of all other windows). Even when focus leaves the gvim window, no other windows can be brought in front of the gvim window. The problem only occurs after an R session has been started with \rf from a gvim window containing an R script. Even when the R session is closed, the gvim window is still stuck on top of any other windows that are open.

This problem is not present in the vim-r-plugin version from the prior commit (aa693aaeae5e0f959d910c7bfac7d2bda3ea869e). The problem appears to be present for all later commits.

**Comment by jalvesaq** [comment] 2015-03-23 23:41
Thanks for reporting the bug!

What happens if you put the line below in your *vimrc*?

```vim
let vimrplugin_arrange_windows = 0
```

**Comment by jalvesaq** [comment] 2015-03-23 23:50
I think that the problem is the `HWND_TOPMOST` in *VimCom/src/app/vimr.c*. It should be `HWND_NOTOPMOST`.

**Comment by zeloff** [comment] 2015-03-24 10:10
I can confirm that the issue was fixed with jalvesaq/VimCom@e8e6f1a169df4f9aaeb9a08f8efa926945bd8f14 (changing `vimplugin_arrange_windows` didn't fix it).

**Comment by jalvesaq** [comment] 2015-03-24 13:16
Thanks for confirming! I released new versions of Vim-R-plugin and vimcom.

**Closed by jalvesaq** 2015-03-24 13:16 UTC

**Comment by azvoleff** [comment] 2015-03-24 13:24
Thanks! (also works here)
